baseURL: https://matheusgp3.github.io/blog/
languageCode: en
DefaultContentLanguage: en
title: Blog do matheus
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
publishDir: docs/
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
taxonomies:
  category: categories
  series: series
  tag: tags
