  [[main]]
  name = "Pagina Principal"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Curriculo"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Sobre mim"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Entrar em contato"
  weight = 500
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "Fase Beta"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"